### ISSUE TITLE
Balance block remains unavailable after a connection lost

### ISSUE THREAD

**Issue by aarrtthhuurr** [simde-utc/payutc-mobile#205] opened 2019-08-23 10:45 UTC
<img width="375" alt="image" src="https://user-images.githubusercontent.com/17085831/63587200-9617e400-c5a3-11e9-8f54-b82e28e195de.png">

How to reproduce ?
- Open the app with data enabled
- Refresh
- Disable you data
- Refresh
- Pop-up says app can't access to the internet
- Close it (dont click on refresh)
- Enable data 
- History is well refreshed but balance block stays in loading

**Comment by NastuzziSamy** [comment] 2019-08-23 19:33
Can't reproduce that even following what you said and retrying many times.

Does it happen again to you ?

**Comment by NastuzziSamy** [comment] 2019-09-05 00:27
Closing due to lack of information

**Closed by NastuzziSamy** 2019-09-05 00:27 UTC
Labels: bug, invalid, question
